[package]
name = "bias-shared-arena"
version = "0.8.5"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"
license = "MIT"
description = "A thread-safe & efficient memory pool "
repository = "https://github.com/binarly-io/bias-shared-arena"
homepage = "https://github.com/binarly-io/bias-shared-arena"
documentation = "https://docs.rs/bias-shared-arena"
keywords = ["memory", "pool", "thread"]
categories = ["memory-management", "concurrency"]
readme = "README.md"
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[lib]
bench = false

[dependencies]
static_assertions = "1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "mempool"
harness = false
